In [2]:
from scipy import sparse
mtx = sparse.lil_matrix([[0,1,0],[1,0,1],[0,0,1]])

In [4]:
print mtx

  (0, 1)	1
  (1, 0)	1
  (1, 2)	1
  (2, 2)	1


In [5]:
mtx.toarray()

array([[0, 1, 0],
       [1, 0, 1],
       [0, 0, 1]])

In [8]:
import numpy as np
np.random.randint?

In [9]:
np.random.randint(0, 5, (15, 2))

array([[0, 1],
       [3, 1],
       [0, 3],
       [4, 3],
       [2, 4],
       [0, 3],
       [2, 0],
       [4, 2],
       [1, 0],
       [4, 0],
       [2, 1],
       [2, 4],
       [4, 0],
       [0, 0],
       [2, 4]])

In [21]:
X = np.random.rand(3,2)

In [22]:
Y = X.T

In [23]:
Y

array([[ 0.00788021,  0.03836558,  0.86953094],
       [ 0.33861338,  0.29913651,  0.01805932]])

In [24]:
X

array([[ 0.00788021,  0.33861338],
       [ 0.03836558,  0.29913651],
       [ 0.86953094,  0.01805932]])

In [20]:
np.random.rand?

In [27]:
X1 = np.random.rand(10)
Y1 = X1[:,np.newaxis]

In [29]:
print Y1.shape
Y1

(10, 1)


array([[ 0.33951954],
       [ 0.47333829],
       [ 0.37441375],
       [ 0.93841992],
       [ 0.4544864 ],
       [ 0.6466301 ],
       [ 0.9096649 ],
       [ 0.34330624],
       [ 0.40479337],
       [ 0.94357347]])

In [30]:
x = np.linspace(1, 12, 10)

In [31]:
x

array([  1.        ,   2.22222222,   3.44444444,   4.66666667,
         5.88888889,   7.11111111,   8.33333333,   9.55555556,
        10.77777778,  12.        ])

In [32]:
y = x[:, np.newaxis]

In [34]:
y * np.sin(x)* np.cos(y)

array([[  0.45464871,   0.42965923,  -0.16114161,  -0.53973765,
         -0.20756183,   0.39794884,   0.47940705,  -0.0704582 ,
         -0.52753818,  -0.28991158],
       [ -1.13378103,  -1.07146346,   0.40184717,   1.3459717 ,
          0.51760767,  -0.99238561,  -1.19552218,   0.17570525,
          1.31554925,   0.72296753],
       [ -2.76649342,  -2.61443483,   0.98053109,   3.28425133,
          1.26299362,  -2.42148015,  -2.91714552,   0.4287313 ,
          3.21001874,   1.76408394],
       [ -0.17948278,  -0.16961762,   0.06361427,   0.21307355,
          0.08193969,  -0.15709923,  -0.18925669,   0.02781495,
          0.20825754,   0.11444911],
       [  4.57509226,   4.32362517,  -1.62155462,  -5.43133511,
         -2.08867742,   4.0045261 ,   4.82423337,  -0.70901498,
         -5.30857286,  -2.91735621],
       [  4.04746749,   3.82500096,  -1.43454804,  -4.80496371,
         -1.84779967,   3.54270215,   4.26787628,  -0.62724748,
         -4.69635908,  -2.58091067],
       [ -

In [38]:
 np.array([[1],[2],[3]])*np.array([1,2,3])*np.array([[2],[2],[2]])

array([[ 2,  4,  6],
       [ 4,  8, 12],
       [ 6, 12, 18]])

In [42]:
import sklearn

In [47]:
from sklearn.datasets import load_iris

In [53]:
bunch_obj = sklearn.datasets.fetch_california_housing()

In [54]:
bunch_obj.keys()

['data', 'feature_names', 'DESCR', 'target']

In [55]:
np.where?